name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://npm.pkg.github.com
        scope: "@stremio"
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install NPM Dependencies
      run: npm install
    - name: Publish to GitHub Package Registry
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish
